 BAD_WORDS = [
            "fuck",
            "fuk",
            "fck",
            "f***",
            "f*ck",
            "f.u.c.k",
            "fu",
            "f u",
            "f.u",
            "fawk",
            "fak",
            "phuck",
            "phuk",
            "shit",
            "sh1t",
            "sh*t",
            "s.h.i.t",
            "sh!t",
            "shiiit",
            "bitch",
            "b!tch",
            "b1tch",
            "b*tch",
            "b i t c h",
            "biatch",
            "pussy",
            "pussi",
            "p*ssy",
            "p.u.s.s.y",
            "pussee",
            "dick",
            "d1ck",
            "d*ck",
            "dik",
            "d.i.c.k",
            "dyck",
            "cock",
            "c0ck",
            "cawk",
            "nega"
            "fvck"
            "kawk",
            "cunt",
            "cu*t",
            "cnt",
            "c.u.n.t",
            "slut",
            "s1ut",
            "s.l.u.t",
            "sloot",
            "whore",
            "wh0re",
            "w.h.o.r.e",
            "hoe",
            "h0e",
            "h03",
            "ass",
            "a55",
            "azz",
            "arse",
            "asshole",
            "a**hole",
            "a**",
            "arsehole",

            "nigga",
            "nigger",
            "niga",
            "n1gga",
            "ni99a",
            "ni**a",
            "ni**er",
            "niga",
            "negro",
            "negga",
            "negra",
            "nigguh",
            "neega",
            "neega",
            "negr",
            "negr0",
            "n3gro",
            "n1gr",
            "chink",
            "chingchong",
            "ching chong",
            "gook",
            "zipperhead",
            "slanty",
            "slant eye",
            "chino",
            "yellowman",
            "rice eater",
            "paki",
            "pak1",
            "pak1stani",
            "raghead",
            "towelhead",
            "camel jockey",
            "sandnigger",
            "gypsy",
            "gyppo",
            "gippo",

            "fag",
            "faggot",
            "fa**ot",
            "f@g",
            "f4g",
            "fgt",
            "fagot",
            "dyke",
            "d1ke",
            "d*ke",
            "d.y.k.e",
            "tranny",
            "trannie",
            "transvestite",
            "shemale",
            "he-she",
            "ladyboy",
            "crossdresser",
            "homo",
            "hom0",
            "queer",

            "retard",
            "retarded",
            "r3tard",
            "r*tard",
            "r3t4rd",
            "spaz",
            "spastic",
            "autist",
            "lamebrain",
            "moron",
            "imbecile",

            "bastard",
            "twat",
            "jerk",
            "loser",
            "scumbag",
            "dipshit",
            "douche",
            "douchebag",
            "fatass",
            "fat ass",
            "fatso",
            "obese",
            "fattie",
            "blubber",

            "kys",
            "k y s",
            "kill yourself",
            "go die",
            "just die",
            "end yourself",
            "unalive yourself",
            "neck yourself",
            "commit die",

            "damn",
            "dammit",
            "hell",
            "d@mn",
            "d@mmit",
            "bastard",
            "bloody",
            "bugger",
            "bollocks",
            "wanker",
            "sod off",
            "tosser",
            "lmfao",
            "lmao",
            "rekt",
            "ez",
            "git gud",
            "gg ez",
            "clapped",

            "cracker",
            "honkey",
            "hillbilly",
            "redneck",
            "yankee",
            "white trash",
            "ape",
            "monkey",
            "coon",
            "savage",
            "caveman",
            "uncivilized",

            "nlgga",
            "nibba",
            "nignog",
            "nogger",
            "niggor",
            "negguh",
            "kneegrow"
        ]

        LOG_CHANNEL_ID = 1366005332840812633  # Replace with your log channel ID

        msg_lower = message.content.lower()
        found_bad = [
            word for word in BAD_WORDS
            if re.search(rf"\b{re.escape(word)}\b", msg_lower)
        ]

        if found_bad:
            try:
                
                await message.delete()
                log_channel = bot.get_channel(LOG_CHANNEL_ID)
                if log_channel:
                    embed = discord.Embed(
                        title="🚨 Rule Violetion Detected",
                        description=(
                            f"**User:** {message.author.mention}\n"
                            f"**Channel:** {message.channel.mention}\n"
                            f"**Message:** ||{message.content}||"),
                        color=discord.Color.red())
                    embed.set_footer(text="Ascented")
                    await log_channel.send(content = "<@&1379102478666301541>", embed=embed)
            except discord.Forbidden:
                print("⚠️ Missing permission to delete or send log.")
            except discord.HTTPException as e:
                print(f"❌ Error deleting or logging: {e}")
            return  # Prevent further processing of deleted message
